services:


  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: SecondHandMarket
      POSTGRES_PASSWORD: secret
    volumes:
      - SecondHandMarket-pg-local:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  SecondHandMarket-pg-local: