spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  sql:
    init:
      mode: ${INIT_DB:always}
      schema-locations: "classpath:db-init.sql"

logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: TRACE # Incoming HTTP requests
    org.springframework.jdbc.datasource.init: DEBUG
    org.springframework.jdbc.core: DEBUG # SQL